### ISSUE TITLE
How many amps the mosfet for the bed can handle?

### ISSUE THREAD

**Issue by valerie16901** [Aus3D/RUMBA-Plus#7]
I am worried that my bed, which is 300x300 12v, can be drawing to much amperage from the bed mosfet, I am currently measuring about 21 amps, should I get an external mosfet instead?

**Comment by chrissbarr** [comment]
Hi @valerie16901!

The bed MOSFET itself should be able to handle 21A without any issue. It will generate a bit of heat, but still less heat than the MOSFETs on a regular RAMPS board would with a 200x200mm 12V bed - so not a dangerous amount. Even without active cooling (i.e., no electronics fan) 21A should be okay - if you want to be doubly safe, a fan blowing over the board should keep the MOSFET's temperature well under control.

The weak link in this setup is the screw terminals on the RUMBA+ board - they're only rated to 15A, and while that rating is likely on the conservative side, that's where you might run into trouble. 

If you're comfortable making a modification to the board, I would suggest de-soldering the heated bed screw terminals (both in and out), and soldering your wires directly to the board instead. That will allow you to run 21A without problems.

If that's not an option, I'd suggest making sure that your heated bed wiring is firmly gripped by the screw terminals, and ensuring that there's no room for the wires to work their way loose. If you can, fix the wires in place near the board with a cable tie, so that no movement of the wires will move the connection inside the screw terminals. A fan, with some air blowing over the screw terminals, would also help a little here.

Without the modifications, I'd also suggest limiting the maximum power delivered to the heated bed - depending on how much power you need to heat it up and how quickly you want it to do so, this might not be an attractive option, but I'd suggest exploring it and seeing if it's workable. In Marlin, the option you're after is `#define MAX_BED_POWER`, which, if set to something less than `255`, should limit the average power being delivered to the bed (and the average current through the screw terminals). The further you reduce it the safer you should be, but then the slower the bed will heat up. If you're running this option, it will put a little more stress on the MOSFET - so I'd definitely suggest running a cooling fan in this case.

The only other thing to watch out for is that the heated bed fuse we supply with these boards is rated to 20A, and might blow running your 21A load - you may have already replaced this, or the included fuse might have enough wiggle-room to run 21A for short periods, but it's something that could blow at some point. A 25A fuse should be easy enough to come by, and as they're common automotive fuses, they're usually not too expensive either - you'd be looking for a mini blade fuse.

The other option, and this will depend on your heated bed and the rest of your setup, might be to swap to 24V. If your heated bed allows 12/24V input, then swapping to 24V input would halve your current draw - making it much safer to use the onboard screw terminals. Most standard stepper motors + drivers shouldn't have an issue with the change and often work better with higher voltages, and RUMBA's onboard 12V regulator would still let you run 2-3 12V fans if needed. Depending on your hotend heater cartridge, you might be able to run it from the 12V regulator too - if it's a 25W unit that should be okay, if it's a 40W unit I'd probably advise against it. 

If the bed is fixed at 12V, that's probably not an option you want to explore - I just thought I'd put it out there.

So, my suggestions would be:

- Solution A: Remove Screw Terminals
   - Allows maximum current to heat bed as quickly as possible
   - Safest overall solution, also prevents cables from coming loose over time
- Solution B: Reduce Strain on Screw Terminals
   - Limit bed power in firmware to reduce stress on screw terminals
   - Ensure wiring is as tightly gripped as possible and cannot work loose
   - Have a fan blowing air past the screw terminals (or some airflow over whole board)
- Solution C: Swap to 24V
   - Requires no modification to board, no limiting of bed current
   - Potentially allows improved motor performance (depends on driver, motor and configuration)
   - Requires investment in new PSU, possibly heater cartridge, possibly bed

If none of these is workable, your idea to swap to an external MOSFET board might be a good one. You probably won't find a board with a better MOSFET, but they should have heavier-duty screw terminals that will give you the needed headroom.

Let me know if you need any more information, and I'll see what I can do!

**Comment by valerie16901** [comment]
Thank you very much for all that information.

I will look at the options, probably I can get a 24v power supply only for the bed, since the rest of my components are rated 12v.

**Comment by chrissbarr** [comment]
No worries at all, happy to help!

That sounds like a solid plan. You can definitely use a separate power supply for the bed (something I didn't consider), so provided the bed can support 24V that sounds like a good option.

Let me know if you have any more questions!

**Comment by wizhippo** [comment]
@chrissbarr Just out of curiosity according to the data sheet of the PSMN1R8-40YLC and the Safe operating chart I see that at 12 volts it should only be about 8amps.  Am I reading the chart wrong or missing some kind of factor due to the heat dissipation of the board.  I'm sure you are right but I'm just trying to understand the datasheet a bit better.

**Comment by chrissbarr** [comment]
@wizhippo No worries at all, happy to help. Safe Operating Charts are always a little misleading at first glance IMO, as you have to really think about what they're showing. Note that the voltage is the drain-source voltage, i.e. the voltage across the MOSFET, and not the supply voltage that you're using (12V/24V etc).

Using the MOSFET as a low-side switch for something like a heated bed, ideally most of the 12V is across the bed, with only a small amount across the MOSFET - it's that small amount we need to consider in the SOA chart.

Assuming the MOSFET is operating in saturation mode (fully on), the drain-source voltage is given by the MOSFET's on-state resistance (RDSon), which is ~ 2mΩ using 5V logic (rating on page 1 or from Fig. 7) and the current flowing through the MOSFET. From Ohm's Law, V=IR, the drain-source voltage at say 15A will be V = 15 x 0.002, or about 0.03V. From the SOA chart, at 0.03V we're in safe territory - not even enough of a voltage drop that it's worth charting, and our likely limit is either given by the total power dissipation, or the total current capability of the MOSFET.

If you're PWMing the MOSFET, you'll change the equation from being primarily conduction losses to primarily switching losses - which take a little more work to calculate. That said, the above shows that we really have an order of magnitude headroom with the MOSFET in this configuration, so even there you won't run into any trouble.

I've tested these MOSFETs as hard as I can on these boards, and I always run into trouble with the screw terminals before anything else - usually around 25A or so they'll be damaged, though I do note they're only rated for 15A (we're looking at improving them on future boards).

If I remove the screw terminals, solder heavy-gauge wire directly to the RUMBA+ board, then there are sections of the PCB itself that are heat-damaged before the MOSFET becomes dangerously hot or becomes damaged. From memory, this happens above 30A or so - it's possible that range could be extended with active cooling.

I've never run into the actual limits of the MOSFET itself. Provided you don't exceed 24V, it shouldn't be possible to physically draw enough current through the board to damage the MOSFET, without first damaging the board or connectors themselves. 

I hope that answers your question! Let me know if not, or if there's anything else I can do for you.

**Comment by wizhippo** [comment]
@chrissbarr Thank you for clear answer.  That makes much more sense to me and your first point is exactly what I was overlooking.

**Comment by chrissbarr** [comment]
@wizhippo No worries at all, it's a mistake I've made before too so I thought that was probably where the mix-up was.

**Comment by Anusuya8** [comment]
Shall I use 24A MOSFET instead of 220A MOSFET for Heat Bed.

**Comment by chrissbarr** [comment]
Hi @Anusuya8!

You'd need to provide more information to figure this out. Is there a part number, datasheet or link for the MOSFET you want to use?

**Comment by Anusuya8** [comment]
Hi @chrissbarr 
We are going to use the MK2B Heat bed in the SKR V1.4 board. In SKR V1.4 board WSK220N04 MOSFET is driving the Heat bed, whose Ids current rating is 220A Since the current of the (MK2B) heat bed is 20A shall I use IRLR8726TRPBF this MOSFET.

**Comment by Anusuya8** [comment]
Hi @chrissbarr <https://github.com/chrissbarr>
We are going to use the MK2B Heat bed in the SKR V1.4 board. In SKR V1.4
board WSK220N04 MOSFET is driving the Heat bed, whose Ids current rating is
220A Since the current of the (MK2B) heat bed is 20A shall I use
IRLR8726TRPBF MOSFET.

Thanks & Regards,
*Ms. Anusuya*
Hardware Engineer

Mob: +91-9962328695


*Embdes Engineering Solutions Pvt. Ltd.,*

No. 567, Mudichur Road, 2nd Floor, SHA Complex,

Lakshmipuram, West Tambaram,

Chennai - 600 045 *|* Tamilnadu *|* India

*GoogleMap*
<https://www.google.com/maps/place/SHA+Complex/@12.925041,80.1009066,15z/data=!4m5!3m4!1s0x0:0x67f5512ade0553c6!8m2!3d12.925041!4d80.1009066>

*www.e2-s.com* <https://e2-s.com/>
