### ISSUE TITLE
[Request] New main power connectors

### ISSUE THREAD

**Issue by Blaster1920** [Aus3D/RUMBA-Plus#8]
Hi,
I'm going to make some of this boards, but I actually disagree with this choice for the Bed and PSU connectors. Instead i found very reliable the Duet's ones, with this model number: TJ952-00.
Do you think that could be possible to modify the board in order to use these?
Thanks you for doing the hard work here providing us a very good board!

**Comment by chrissbarr** [comment]
Hi @Blaster1920,

Thanks for your kind words!

You're welcome to make a change to the power connectors, or to change the board however you'd like. I'm open to swapping the connectors on the boards we manufacture if there's a good reason for doing so - but I think swapping to the part you suggest might be tricky.

I wasn't able to find a datasheet, but from what I can see the TJ952 are 7.62mm pin spacing, whereas the RUMBA+ board currently has spacing for 5mm screw terminals on the power / heated bed connectors. So swapping to the TJ952 would take up more space width-wise, and we'd either have to make the board wider, or remove something else to make some room. We're trying to keep the layout and dimensions as compatible with the original RUMBA boards as possible, and if we had to make the board bigger that might interfere with that (and obviously we're not keen on removing anything).

The screw terminals we use are meant to be a good mix of size, price and reliability - but there are some other drop-in parts you can explore. Pheonix Contact make some nice [5mm pitch screw terminals that can handle down to 12AWG and carry 20A](https://www.digikey.com/product-detail/en/phoenix-contact/1935776/277-6405-ND/2513905) - we don't use them because they're a bit taller and take up more depth on the board (so they cover up some of the silkscreen labelling), but they are a little easier to use and will handle thicker wiring.

If you really want to use the TJ952, one possible option might be to combine the main power and bed power inputs into a single terminal, so that there would only be two connectors instead of three. I'm not overly keen on doing that with our boards, as we like the flexibility of the separate connectors - but if you're looking to make changes yourself, perhaps that's something to consider.

**Comment by Blaster1920** [comment]
Thanks for your reply.
I think that I will modify a little the PCB to remove the hole behind the connectors so I can move there the labels and then use my connector. I'll upload the files if you would like to give them a look.

**Comment by Blaster1920** [comment]
I would also like to use thicker copper, how much micron do you suggest?

**Comment by chrissbarr** [comment]
Hi @Blaster1920,

Just an update on this. We've updated the screw terminals a little in our latest v1.4 revision. There's still no easy way to fit the connectors you suggested, but there is now room to fit Phoenix Contact 1935776 - which suit up to 10AWG wire and 20A of current. We're using these connectors on new boards that are shipping now.

As for copper thickness - it depends on what your goal is. The default 1 oz copper is sufficient for running a 20A heated bed. If you need more than that, then you'll need to:

- Upgrade the connectors as you planned, to something that can carry the current you're after
- Use a higher-current fuse, or fuse the bed externally and jumper the fuse
- Cool the bed MOSFET, either with a heatsink, fan, or both, depending on how much current you plan to put through it.

You'll need to figure those things out before there's any value in using thicker copper. If you sort those out, then it could be worth stepping up to 2 oz copper.
